Bemirps, Emirps, Primes, Composite & FUN

A prime number is a number whose only proper (non-self) divisor is 1 (example 13).

An emirp (prime spelled backwards) is a non-palindromic prime which, when its digits are reversed, makes another prime. E.g. 13 is a prime, and so is 31. Both are therefore emirps.

A bemirp is a prime which is an emirp (makes another prime with its digits reversed), but additionally, makes another prime when flipped upside down (see note). The upside-down version is also an emirp, which makes a group of 4 primes.

To illustrate: 11061811, reversed = 11816011, upside-down = 11091811, upside-down reversed = 11819011. All four are primes.

Create a program that takes 'N' number of numbers and for each number it returns "B" if it’s a bemirp, "E" if it's a (non-bemirp) emirp, "P" if it's a (non-emirp) prime, or "C" (composite / non-prime).

Notes

6 upside-down is 9 and vice-versa. 0, 1, and 8 are unchanged when flipped. The remaining five digits are unflippable.

### Numpy:


* Numpy ---- Numerical Python
* Numpy is a library in python which is used to built different dimensional arrays.

In [10]:
import numpy as np
a=[1,2,3,4,5]
data=np.array(a)
print(data)

[1 2 3 4 5]


In [11]:
a

[1, 2, 3, 4, 5]

In [13]:

data1=np.array([[1,2,3,4],[3,4,5,6]])

In [14]:
data1

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [15]:
type(data1)

numpy.ndarray

In [16]:
data2=np.array([[1,2,3,4],[2,3,4,5],[4,5,6,7]])

In [19]:
data2.shape

(3, 4)

In [24]:
## arranging data in an array:

data=np.arange(0,101)
print(data)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


In [25]:
data.shape

(101,)

In [31]:
data=np.arange(0,100)
data
data2=data.reshape(10,10)
data2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [34]:
data2=np.linspace(0,8,20)
data2

array([0.        , 0.42105263, 0.84210526, 1.26315789, 1.68421053,
       2.10526316, 2.52631579, 2.94736842, 3.36842105, 3.78947368,
       4.21052632, 4.63157895, 5.05263158, 5.47368421, 5.89473684,
       6.31578947, 6.73684211, 7.15789474, 7.57894737, 8.        ])

In [38]:
data=np.random.randint(0,20,size=(2,4))
data

array([[13,  7,  5, 14],
       [16, 13, 13, 16]])

In [42]:
data=np.ones((4,3),int)
data


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [45]:
data=np.zeros((4,3),int)
data

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [47]:
n=np.ones((4,3),int)
n
np.vstack([n,n*10])

array([[ 1,  1,  1],
       [ 1,  1,  1],
       [ 1,  1,  1],
       [ 1,  1,  1],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [49]:
n=np.ones((4,3),int)
n
np.hstack([n,n*2])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

### Operators:

In [52]:
n1=np.array([1,2,3,4])
n2=np.array([2,3,4,5])
n1,n2
n1+n2

array([3, 5, 7, 9])

In [53]:
n1-n2

array([-1, -1, -1, -1])

In [54]:
n1*n2

array([ 2,  6, 12, 20])

In [55]:
n1,n2

(array([1, 2, 3, 4]), array([2, 3, 4, 5]))

In [56]:
n1/n2


array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [57]:
n1**n2

array([   1,    8,   81, 1024], dtype=int32)

In [58]:
n1%n2

array([1, 2, 3, 4], dtype=int32)

In [59]:
n1**3

array([ 1,  8, 27, 64], dtype=int32)

In [63]:
n1&n2

array([0, 2, 0, 4], dtype=int32)

In [64]:
n1.dot(n2)

40

In [66]:
data1

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [67]:
data1.T

array([[1, 3],
       [2, 4],
       [3, 5],
       [4, 6]])

In [70]:
print(data1.transpose())

[[1 3]
 [2 4]
 [3 5]
 [4 6]]


In [72]:
data1

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [73]:
data1.max()

6

In [74]:
data1.min()

1

In [75]:
data1.sum()

28

In [76]:
data1.mean()

3.5

In [77]:
data1

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [78]:
data1[::-1]

array([[3, 4, 5, 6],
       [1, 2, 3, 4]])

In [79]:
np.log(data1)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.09861229, 1.38629436, 1.60943791, 1.79175947]])

In [80]:
np.sin(data1)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ]])

In [81]:
np.sqrt(data1)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [1.73205081, 2.        , 2.23606798, 2.44948974]])